kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: octoprint-claim
  namespace: octoprint
spec:
  storageClassName: nfs-client
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
