apiVersion: v1
kind: Service
metadata:
  name: octoprint-service
  namespace: octoprint
  annotations:
    metallb.universe.tf/ip-allocated-from-pool: first-pool
    metallb.universe.tf/loadBalancerIPs: 192.168.73.24
spec:
  selector:
    app: octoprint
  type: LoadBalancer
  ports:
    - name: octoprint-port
      protocol: TCP
      port: 80
      targetPort: 8080
